version: '3'
services:
  envoy:
    image: envoyproxy/envoy
    ports:
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./proto.pb:/etc/envoy/proto.pb
  
  api:
    image: alpine
    volumes:
      - ./target/release/api:/tmp/api
    command: /tmp/api

  cache:
    image: eqalpha/keydb
    #6379
    volumes:
      - ./keydb_master.conf:/etc/keydb/keydb.conf

