version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    ports:
      - "443:51051"
#    restart: always
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./api_pb.bin:/etc/envoy/api_pb.bin:ro
      - ./ncat:/tmp/netcat
      - certbot_conf:/etc/letsencrypt:ro
    depends_on:
      - api
      - certbot
    command:  bash -c "envoy -c /etc/envoy/envoy.yaml|/tmp/netcat fluentbit 8888"

  certbot:
    image: certbot/certbot:latest
    command: certonly --standalone --agree-tos --email zacharie.bugaud@laposte.net --preferred-challenges http -d api.conv911.com
    volumes:
      - certbot_conf:/etc/letsencrypt
    ports:
      - "80:80"

  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    depends_on:
      - envoy
    restart: always
    env_file:
      - fluentbit.env
  #  network_mode: host
  
  api:
    image: golang:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
    #x86_64-unknown-linux-musl
      - ../target/debug/api:/tmp/api
    entrypoint: ["/tmp/api"]
    depends_on:
      - db
      - cache
    env_file:
      - api.env
      - mongodb.env

  cache:
    image: eqalpha/keydb:latest
    ports:
      - 6380:6379
    volumes:
      - ./keydb_master.conf:/etc/keydb/keydb.conf:ro
    depends_on:
      - db
    restart: always

  db:
    image: bitnami/mongodb:latest
    restart: always
  #  command: --replSet rs0
    ports:
      - "27018:27017"
    env_file:
      - mongodb.env
    volumes:
      - ./mongodata:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
 # certbot_www:
  certbot_conf:
 # logs:
 #   external: false
