version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    ports:
      - "51051:51051"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./api_pb.bin:/etc/envoy/api_pb.bin:ro
      - ./ncat:/tmp/netcat
    depends_on:
      - api
    command:  bash -c "envoy -c /etc/envoy/envoy.yaml|/tmp/netcat fluentbit 8888"
  
  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    depends_on:
      - envoy
    env_file:
      - fluentbit.env
  #  network_mode: host
  
  api:
    image: golang:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
    #x86_64-unknown-linux-musl
      - ../target/debug/api:/tmp/api
    entrypoint: ["/tmp/api"]
    depends_on:
      - db
      - cache
    env_file:
      - api.env
      - mongodb.env

  cache:
    image: eqalpha/keydb:latest
 #   ports:
 #     - 6380:6379
    volumes:
      - ./keydb_master.conf:/etc/keydb/keydb.conf:ro
    depends_on:
      - db

  db:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - mongodb.env
    volumes:
      - ./mongodata:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  logs:
 #   external: false
