version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    ports:
      - "3000:51051"
      - "8080:8080"
    restart: always
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./api_pb.bin:/etc/envoy/api_pb.bin:ro
      - ./ncat:/tmp/netcat
      - certbot_conf:/etc/letsencrypt/
    depends_on:
      - api
      - certbot
      - fluentbit
    environment:
      - ENVOY_UID=0
    command:  bash -c "envoy   -c /etc/envoy/envoy.yaml|/tmp/netcat fluentbit 8888"

  certbot:
    build: ./certbot
    volumes:
      - certbot_conf:/etc/letsencrypt/
    ports:
      - "80:80"
    restart: always

  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    restart: always
    
    env_file:
      - fluentbit.env
    
    
  #  network_mode: host
  
  api:
    image: golang:latest
    restart: always
#    ports:
#      - "3000:3000"
    volumes:
    #x86_64-unknown-linux-musl
      - ./api:/tmp/api
    entrypoint: ["/tmp/api"]
    depends_on:
      - db
      - cache
    env_file:
      - api.env
      - mongodb.env

  cache:
    image: eqalpha/keydb:latest
    ports:
      - 6380:6379
    volumes:
      - ./keydb_master.conf:/etc/keydb/keydb.conf:ro
    depends_on:
      - db
    restart: always

  db:
    image: bitnami/mongodb:latest
    restart: always
  #  command: --replSet rs0
    ports:
      - "27018:27017"
    env_file:
      - mongodb.env
    volumes:
     # - ./mongodata:/data/db
      - ./mongodata:/bitnami/mongodb
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
 # certbot_www:
  certbot_conf:
 # logs:
 #   external: false
