resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      tls_certificate:
          certificate_chain:
              filename: "/etc/letsencrypt/live/api.conv911.com/fullchain.pem"
          private_key:
              filename: "/etc/letsencrypt/live/api.conv911.com/privkey.pem"
